### ISSUE TITLE
Can't create standalone launcher

### ISSUE THREAD

**Issue by mac1202** [Wintermute0110/plugin.program.advanced.emulator.launcher#15]
Hi just upgraded to latest version i got an error when I try to create a standalone launcher
```

23:13:16 T:140391131113216   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('launchers_thumb_dir',)
                                            Traceback (most recent call last):
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/addon.py", line 45, in <module>
                                                plugin.run_plugin()
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 197, in run_plugin
                                                self._command_add_new_launcher(args['catID'][0])
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 720, in _command_add_new_launcher
                                                thumb_path  = self.settings['launchers_thumb_dir']
                                            KeyError: ('launchers_thumb_dir',)
                                            -->End of Python script error report<--
```

**Comment by Wintermute0110** [comment]
Bug confirmed. Should be fixed in last commit.

**Comment by mac1202** [comment]
Yes fixed thanks.
