### ISSUE TITLE
Error with latest commit

### ISSUE THREAD

**Issue by mac1202** [Wintermute0110/plugin.program.advanced.emulator.launcher#17]
Hi commit 0d927b6c1e9218ac939be150a311b785461bf091 introduce a new error when adding rom : 

```
18:00:56 T:140080316393216   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: write() argument 1 must be unicode, not str
                                            Traceback (most recent call last):
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/addon.py", line 47, in <module>
                                                plugin.run_plugin()
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 218, in run_plugin
                                                self._command_add_roms(args['launID'][0])
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 1447, in _command_add_roms
                                                self._roms_import_roms(launcher)
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 4431, in _roms_import_roms
                                                fs_write_ROMs(ROMS_DIR, selectedLauncher['roms_base_noext'], roms, selectedLauncher)
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/disk_IO.py", line 421, in fs_write_ROMs
                                                fs_write_ROMs_JSON(roms_dir, roms_base_noext, roms, launcher)
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/disk_IO.py", line 638, in fs_write_ROMs_JSON
                                                file.write(json_unicode.encode('utf-8'))
                                            TypeError: write() argument 1 must be unicode, not str
                                            -->End of Python script error report<--
```

**Comment by Wintermute0110** [comment]
Try now please. Apparently is was a bug in Python 2. I found a patch in StackOverflow that should do the job.

**Comment by mac1202** [comment]
Fixed, thanks.
