### ISSUE TITLE
Error when starting a rom

### ISSUE THREAD

**Issue by mac1202** [Wintermute0110/plugin.program.advanced.emulator.launcher#19]
Hi, AEL failed to start rom with this error

```
19:17:12 T:140030172088064   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'VLAUNCHER_FAV_ID' is not defined
                                            Traceback (most recent call last):
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/addon.py", line 47, in <module>
                                                plugin.run_plugin()
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 226, in run_plugin
                                                self._command_run_rom(args['catID'][0], args['launID'][0], args['romID'][0])
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 3671, in _command_run_rom
                                                if launcherID == VLAUNCHER_FAV_ID:
                                            NameError: global name 'VLAUNCHER_FAV_ID' is not defined
                                            -->End of Python script error report<--
```

No problem to start standalone programs.

**Comment by jader9920** [comment]
I'm getting this too, was just coming to ask about it

**Comment by Wintermute0110** [comment]
This is unrelated with #18 , will fix ASAP.

**Comment by Wintermute0110** [comment]
Fixed launching of ROMs in Favourites. Still working on the Collections, but Favoruites should work now.

**Comment by jader9920** [comment]
Getting this when launching from favorites:

> 13:40:56 T:12320   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\u201c' in position 41: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\jader\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\addon.py", line 47, in <module>
                                                plugin.run_plugin()
                                              File "C:\Users\jader\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 226, in run_plugin
                                                self._command_run_rom(args['catID'][0], args['launID'][0], args['romID'][0])
                                              File "C:\Users\jader\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 3799, in _command_run_rom
                                                startproc = subprocess_hack.Popen(r'%s %s' % (application, arguments), cwd=apppath, startupinfo=info)
                                              File "C:\Users\jader\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\subprocess_hack.py", line 544, in __init__
                                                errread, errwrite)
                                              File "C:\Users\jader\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\subprocess_hack.py", line 707, in _execute_child
                                                startupinfo)
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 41: ordinal not in range(128)
                                            -->End of Python script error report<--

>

**Comment by Wintermute0110** [comment]
OK, this new issue is new an related with Unicode. I need you to verify this:

1) Does the same problem happen when you launch the ROM from its launcher instead of Favourites.

2) If so: A) Turn OFF all debug settings of Kodi. B) In AEL, Setting -- Advanced turn ON AEL DEBUG. C) Reproduce the bug under this conditions and post the whole log in pastebin. I will be able to see the characters of your launching program and arguments to track down the problem.

**Comment by jader9920** [comment]
1. It happens no matter where I launch from.

2. If this is not the correct log let me know:  http://pastebin.com/d8m0TAhD

**Comment by Wintermute0110** [comment]
That log is perfect. I think I know what happens. You are using the typographical quote “ instead of the normal ASCII QUOTE " and hence the problem. Try to change it and report results.

**Comment by jader9920** [comment]
Removed quotes from the launch parameters, PS2 is working now, I am still getting an error when attempting to launch Gamecube games. Is this the same type of error?

> 11:23:30 T:5712   ERROR: AEL INFO : _command_run_rom() Launching ROM in Launcher...
11:23:30 T:5712   ERROR: AEL VERB : fs_load_ROMs_JSON() Loading JSON file C:\Users\jader\AppData\Roaming\Kodi\userdata\addon_data\plugin.program.advanced.emulator.launcher\db_ROMs\roms_Emulators_Gamecube_538ff1.json
11:23:30 T:5712   ERROR: AEL INFO : _command_run_rom() categoryID  = 807a1389fb355d6cb47ccfa517701945
11:23:30 T:5712   ERROR: AEL INFO : _command_run_rom() launcherID  = 538ff12b4f8115727767a12b92b09bb9
11:23:30 T:5712   ERROR: AEL INFO : _command_run_rom() romID       = 417f2ec2f57f229decd950f1d8f62671
11:23:30 T:5712   ERROR: AEL INFO : _command_run_rom() application = "D:\Dolphin\Dolphin.exe"
11:23:30 T:5712   ERROR: AEL INFO : _command_run_rom() apppath     = "D:\Dolphin"
11:23:30 T:5712   ERROR: AEL INFO : _command_run_rom() romfile     = "D:\Roms\Nintendo GameCube\Games\Animal Crossing.iso"
11:23:30 T:5712   ERROR: AEL INFO : _command_run_rom() rompath     = "D:\Roms\Nintendo GameCube\Games"
11:23:30 T:5712   ERROR: AEL INFO : _command_run_rom() rombasename = "Animal Crossing.iso"
11:23:30 T:5712   ERROR: AEL INFO : _command_run_rom() arguments   = "/B –exec= D:\Roms\Nintendo GameCube\Games\Animal Crossing.iso"
11:23:30 T:5712   ERROR: AEL VERB : _run_before_execution() media_state is "Stop" (0)
11:23:30 T:5712   ERROR: AEL VERB : _run_before_execution() Toggling Kodi fullscreen DEACTIVATED in Launcher
11:23:30 T:5712   ERROR: AEL VERB : _run_before_execution() Calling xbmc.enableNavSounds(False)
11:23:30 T:5712   ERROR: AEL VERB : _run_before_execution() Pausing 500 ms
11:23:30 T:5712   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\u2013' in position 26: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\jader\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\addon.py", line 47, in <module>
                                                plugin.run_plugin()
                                              File "C:\Users\jader\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 226, in run_plugin
                                                self._command_run_rom(args['catID'][0], args['launID'][0], args['romID'][0])
                                              File "C:\Users\jader\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 3799, in _command_run_rom
                                                startproc = subprocess_hack.Popen(r'%s %s' % (application, arguments), cwd=apppath, startupinfo=info)
                                              File "C:\Users\jader\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\subprocess_hack.py", line 544, in __init__
                                                errread, errwrite)
                                              File "C:\Users\jader\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\subprocess_hack.py", line 707, in _execute_child
                                                startupinfo)
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 26: ordinal not in range(128)
                                            -->End of Python script error report<--

**Comment by jader9920** [comment]
Disregard the last comment. 
I figured out what was wrong, I was putting the launch arguments in the wrong order so the quotes were passing to AEL instead of the emulator itself.
It works now.
