### ISSUE TITLE
cant not add roms (release verison)

### ISSUE THREAD

**Issue by eggfoo** [Wintermute0110/plugin.program.advanced.emulator.launcher#21]
windows 7
jarvis kodi
release version of AEL

adding this here as well at the linked release page.

```
18:38:46 T:67556   ERROR: XFILE::CDirectory::GetDirectory - Error getting /extrafanart/
18:38:46 T:69988   ERROR: XFILE::CDirectory::GetDirectory - Error getting D:\Arcade\\\extrathumb\
18:38:46 T:69988   ERROR: Previous line repeats 6 times.
18:38:46 T:69988   ERROR: XFILE::CDirectory::GetDirectory - Error getting /extrafanart/
18:38:46 T:67556   ERROR: CImageLoader::DoWork - Direct texture file loading failed for resource://resource.images.studios.white/
18:38:46 T:67556   ERROR: XFILE::CDirectory::GetDirectory - Error getting /extrafanart/
18:38:46 T:68104   ERROR: Previous line repeats 11 times.
18:38:46 T:68104   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('7afbbc7475e255a5974383cc9366249e',)
                                            Traceback (most recent call last):
                                              File "C:\Users\hteapeac\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\addon.py", line 47, in <module>
                                                plugin.run_plugin()
                                              File "C:\Users\hteapeac\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 204, in run_plugin
                                                self._command_render_launchers(args['catID'][0])
                                              File "C:\Users\hteapeac\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 2034, in _command_render_launchers
                                                category_name = self.categories[categoryID]['m_name']
                                            KeyError: ('7afbbc7475e255a5974383cc9366249e',)
                                            -->End of Python script error report<--
18:38:46 T:63932   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.advanced.emulator.launcher/?catID=7afbbc7475e255a5974383cc9366249e&com=SHOW_LAUNCHERS
18:38:46 T:63932   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.advanced.emulator.launcher/?catID=7afbbc7475e255a5974383cc9366249e&com=SHOW_LAUNCHERS) failed
18:38:46 T:69988   ERROR: XFILE::CDirectory::GetDirectory - Error getting D:\Arcade\\K: (SLUS_00067)\extrafanart\
18:38:50 T:70152 WARNING: VIDEO::CVideoInfoScanner::Process directory 'smb://FREENAS/media1/Media/Completed/TVShows/Shameless (US)/' does not exist - skipping scan.
18:38:50 T:70152  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:14
18:41:03 T:67396   ERROR: XFILE::CDirectory::GetDirectory - Error getting D:\Arcade\\Advanced Emulator Launcher\extrafanart\
18:41:05 T:69416   ERROR: XFILE::CDirectory::GetDirectory - Error getting D:\Arcade\\{ROM Collections}\extrafanart\
18:41:06 T:69896   ERROR: XFILE::CDirectory::GetDirectory - Error getting D:\Arcade\\<Favourites>\extrafanart\
18:41:07 T:69896   ERROR: XFILE::CDirectory::GetDirectory - Error getting D:\Arcade\\Emulators\extrafanart\
18:41:17 T:69896   ERROR: XFILE::CDirectory::GetDirectory - Error getting D:\Arcade\\Nintendo\extrafanart\
18:41:18 T:67396   ERROR: XFILE::CDirectory::GetDirectory - Error getting D:\Arcade\\..\extrafanart\
18:41:21 T:69896   ERROR: XFILE::CDirectory::GetDirectory - Error getting D:\Arcade\\Nintendo\extrafanart\
18:41:35 T:70552   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'rom_asset_list' is not defined
                                            Traceback (most recent call last):
                                              File "C:\Users\hteapeac\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\addon.py", line 47, in <module>
                                                plugin.run_plugin()
                                              File "C:\Users\hteapeac\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 228, in run_plugin
                                                self._command_add_roms(args['launID'][0])
                                              File "C:\Users\hteapeac\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 1486, in _command_add_roms
                                                self._roms_add_new_rom(launcher)
                                              File "C:\Users\hteapeac\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 4493, in _roms_add_new_rom
                                                self.enabled_asset_list = [False] * len(rom_asset_list)
                                            NameError: global name 'rom_asset_list' is not defined
                                            -->End of Python script error report<--
```

**Comment by Wintermute0110** [comment]
Issue should be fixed in 0.9.1. Have a try and close the issue if so.

**Comment by eggfoo** [comment]
Will test tonight when home. 
Sorry for being annoying. Didn't realize you were on holiday. Thanks mate

**Comment by eggfoo** [comment]
fixed.

and dude... you added all meta data as XML file for tons of systems?!?
awesome!
