### ISSUE TITLE
Scraping metadata stop working

### ISSUE THREAD

**Issue by mac1202** [Wintermute0110/plugin.program.advanced.emulator.launcher#28]
Hi with latest git version I can no longer scrape metadata, here the error in kodi.log : 
```
21:50:19.196 T:139866616624896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'text_clean_ROM_name_for_scraping' is not defined
                                            Traceback (most recent call last):
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/addon.py", line 42, in <module>
                                                plugin.run_plugin()
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 243, in run_plugin
                                                self._command_add_roms(args['launID'][0])
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 1793, in _command_add_roms
                                                self._roms_import_roms(launcher)
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 6414, in _roms_import_roms
                                                romdata     = self._roms_process_scanned_ROM(launcherID, ROM)
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 6619, in _roms_process_scanned_ROM
                                                romdata[A.key] = self._roms_scrap_asset(asset_kind, local_asset_list[i], ROM, launcher)
                                              File "/home/mac/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 6678, in _roms_scrap_asset
                                                rom_name_scraping = text_clean_ROM_name_for_scraping(ROM.getBasename_noext())
                                            NameError: global name 'text_clean_ROM_name_for_scraping' is not defined
                                            -->End of Python script error report<--
```

**Comment by mac1202** [comment]
Fixed with https://github.com/Wintermute0110/plugin.program.advanced.emulator.launcher/commit/624b273944f86051a9a34c9688c80e3e58404524 thank you
