### ISSUE TITLE
Scanning ROMs with Metadata Scan Policy set to NFO Files generates error

### ISSUE THREAD

**Issue by smoothquark** [Wintermute0110/plugin.program.advanced.emulator.launcher#31]
HI! Looks like I am stress testing your great work!
When scanning ROMs with "Metadata Scan Policy" set to "NFO Files" and "Add ROMs -> Scan for New ROMS" generates an error...

 `11:37:09 T:140658618652416   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: FileName instance has no attribute 'path_noext'
                                            Traceback (most recent call last):
                                              File "/home/ramesh/.kodi/addons/plugin.program.advanced.emulator.launcher/addon.py", line 42, in <module>
                                                plugin.run_plugin()
                                              File "/home/ramesh/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 243, in run_plugin
                                                self._command_add_roms(args['launID'][0])
                                              File "/home/ramesh/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 1789, in _command_add_roms
                                                self._roms_import_roms(launcher)
                                              File "/home/ramesh/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 6446, in _roms_import_roms
                                                romdata     = self._roms_process_scanned_ROM(launcherID, ROM)
                                              File "/home/ramesh/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 6554, in _roms_process_scanned_ROM
                                                nfo_file_path = FileName(ROM.path_noext + ".nfo")
                                            AttributeError: FileName instance has no attribute 'path_noext'
                                            -->End of Python script error report<--
`

Error is not generated if "Add ROMs -> Manually  Add ROM". The ROM is added but the .nfo file is not read. Looking at your code in main.py line 6234, this appears to be expected behaviour and the metadata is meant to be added manually?

I think the first error is due to line 6563 in main.py:
`nfo_file_path = FileName(ROM.path_noext + ".nfo")`

Should be:
`nfo_file_path = FileName(ROM.getPath_noext() + ".nfo")`

Corrects the first error - All the ROMS are added and .nfo files are read with "Add ROMs -> Scan for New ROMS" but the second observation remains with "Add ROMs -> Manually  Add ROM". The ROM is added but the .nfo file is not read. I presume this is expected.

**Comment by Wintermute0110** [comment]
Thanks :) Will fix ASAP.

**Comment by Wintermute0110** [comment]
Hi. I think this issue has been solved. I will close it now. Reopen if the bug is still there.
