### ISSUE TITLE
Metadata scrapping not working (v 0.9.7)

### ISSUE THREAD

**Issue by SimonGhislain** [Wintermute0110/plugin.program.advanced.emulator.launcher#62]
Hi, and thanks for this great addon.

I can't get the scrapper to work. They all throw error messages.
For example, AEL/metadata/scrap from TheGamesDB can correctly find my Witcher 3 standalone shortcut and recognize it as witcher 3, but selecting any items in the list (for example : The Witcher 3 : wild hunt - PC) results in an error.

Here is the log entry :

> 
>  22:06:30.329 T:7964   ERROR: AEL ERROR: SingleInstance::__exit__() Unhandled excepcion in protected code
> 22:06:30.339 T:7964   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.KeyError'>
>                                             Error Contents: u'studio'
>                                             Traceback (most recent call last):
>                                               File "C:\Users\Simon\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\addon.py", line 39, in <module>
>                                                 main.Main().run_plugin()
>                                               File "C:\Users\Simon\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 270, in run_plugin
>                                                 self.run_protected(command, args)
>                                               File "C:\Users\Simon\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 358, in run_protected
>                                                 self._command_edit_launcher(args['catID'][0], args['launID'][0])
>                                               File "C:\Users\Simon\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 1265, in _command_edit_launcher
>                                                 if not self._gui_scrap_launcher_metadata(launcherID, scraper_obj): return
>                                               File "C:\Users\Simon\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 9371, in _gui_scrap_launcher_metadata
>                                                 self.launchers[launcherID]['m_studio'] = gamedata['studio']
>                                             KeyError: u'studio'
>                                             -->End of Python script error report<--
> 

I already tried with a fresh install of 0.9.7. Any other ideas ?

**Comment by Wintermute0110** [comment]
Can you please try development version in branch `release-0.9.8` and report back?

**Comment by SimonGhislain** [comment]
Just installed the dev version 0.9.8. It allowed the scrapping of all the text data, but none of the images were scrapped (boxart, fanart, clearlogo, etc.).
No error messages were shown, and there's nothing anormal in the log.
I checked TheGamesDB to check if the selected game had Boxart, etc. and it does.

Does this version support scrapping of pictures ?

**Comment by Wintermute0110** [comment]
All scrapers should work in the `release-0.9.8` branch. Have you tried any other ROMs with TheGamesDB scraper? Maybe there is some issue in particular with that ROM. 

Also, are you using an skin with AEL support? Wheter the answer is yes or no, to check if the image is present you have 2 ways: a) Go to the ROM and open the context menu, select "View ROM/Launcher", then select "View ROM data". Scroll down until you see the `s_*` fields, which are the database entry for the artwork. Are they empty or point to a file? b) Go to the ROM and open the context menu, select "Edit ROM", then "Edit Assets/Artwork". In the select dialog you should see an icon of the artwork pieces you have.

Last, if you want me to check that particular ROM please provide a complete debug log. Set AEL log level to DEBUG, reboot Kodi, open AEL and scrape a couple of artwork pieces for that particular ROM and then upload the log. Please provide the *complete* debug log and not only a piece of it. Then, I will be able to create a fake ROM with the same name to try to reproduce your issue and fix it.

**Comment by SimonGhislain** [comment]
Hello,
I read your reply and it got me thinking.
In AEL, i only used the launchers. So, without creating any category (in the root category), i would add standalone launchers (each launcher poiting to a windows shortcut for games). Once the standalone launcher was created, I would use the context menu to scrape metadata for the whole launcher. And that works nicely, except for the images.
From what I understand know, it's more about ROMs than launchers. So, today, I created a launcher for WINDOWS (lnk), and inside that launcher I set up a ROM path pointing to the folder containing all the shortcuts. 
And magic happened.
AEL scanned the whole content of the folder and added one by one all the metadata, including images. I feel kind of dumb now, because I imagine that this is the way AEL is supposed be used ;-)

So yes, my issue is solved in that matter. But just to let you know, picture scrapping do not seem to work for games if sent as standalone launchers (it works fine when those games are set as ROM in a LNK launcher).

I will let you reply if that behaviour is normal or not, and will close the issue accordingly.
I really appreciate the energy you put into solving issues for your awesome addon !

**Comment by Wintermute0110** [comment]
OK. I will have a look to scraping in standalone launchers. It is possible there is a bug. It will take some time, I will let you know when ready.

**Comment by Wintermute0110** [comment]
I had a quick look at this issue today. Scrapers for standalone launchers are not enabled. I will enable them for version 0.9.9 and put this issue in the TODO file.
