### ISSUE TITLE
Error creating standalone launcher

### ISSUE THREAD

**Issue by Anntoin** [Wintermute0110/plugin.program.advanced.emulator.launcher#65]
Hi,

Getting the following error when trying to create a standalone launcher

```
23:12:54.893 T:140498625390336   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'assets_path'
                                            Traceback (most recent call last):
                                              File "/var/lib/kodi/.kodi/addons/plugin.program.advanced.emulator.launcher/addon.py", line 39, in <module>
                                                main.Main().run_plugin()
                                              File "/var/lib/kodi/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 305, in run_plugin
                                                self.run_protected(command, args)
                                              File "/var/lib/kodi/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 389, in run_protected
                                                self._command_add_new_launcher(args['catID'][0])
                                              File "/var/lib/kodi/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 988, in _command_add_new_launcher
                                                builder.createLauncher(categoryID, self.launchers, self.categories, self.settings, CATEGORIES_FILE_PATH)
                                              File "/var/lib/kodi/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/launcher_builder.py", line 168, in createLauncher
                                                assets_init_asset_dir(FileNameFactory.create(launcher['assets_path']), launcher)
                                            KeyError: 'assets_path'
                                            -->End of Python script error report<--
```

**Comment by Wintermute0110** [comment]
Hi. Master branch is undergoing a huge refactoring for release 0.9.9. Please install 0.9.7 from the ZIP file or try branch `release-0.9.8`. I will close the issue now.
