### ISSUE TITLE
Error when attempting to add a trailer file (Mp4 format)

### ISSUE THREAD

**Issue by eggfoo** [Wintermute0110/plugin.program.advanced.emulator.launcher#7]
Listed below is the kodi.log Error that i get when i try to add a trailer to one of my roms.

-Kodi v.16 Jarvis
-Windows 7
(Rdyott on kodi forums)

https://youtu.be/QSuT1Dh-2PI

```
18:45:51 T:7396   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'app' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\Monki\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\addon.py", line 45, in <module>
                                                plugin.run_plugin()
                                              File "C:\Users\Monki\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\main.py", line 237, in run_plugin
                                                self._command_edit_rom(args['catID'][0], args['launID'][0], args['romID'][0])
                                              File "C:\Users\Monki\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\main.py", line 1397, in _command_edit_rom
                                                if not app: return
                                            UnboundLocalError: local variable 'app' referenced before assignment
                                            -->End of Python script error report<--
```

**Comment by Wintermute0110** [comment]
OK. I do not use videos at all so didn't test this feature. Will have a look ASAP.

**Comment by eggfoo** [comment]
thank you. I want to keep using/testing this addon. So far its very nice indeed.

**Comment by Wintermute0110** [comment]
Should be fixes now. Please try. Also, open more bug reports if you find more issues (I'm sure there will be more bugs due to the complexity of the code).

**Comment by eggfoo** [comment]
fix confirmed.
will report any new bugs i find.
